// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs0IYKq6tyLjP-TGRE5LPwjhPG2axdmHM',
    appId: '1:1009236955342:web:2dc84000af2d58d38ec09f',
    messagingSenderId: '1009236955342',
    projectId: 'ecommerce-53a37',
    authDomain: 'ecommerce-53a37.firebaseapp.com',
    storageBucket: 'ecommerce-53a37.firebasestorage.app',
    measurementId: 'G-CRYETN2F89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjEfegrGw9aE8DINxzDDyaa_A2wV-uoYs',
    appId: '1:1009236955342:android:267528315a95d9948ec09f',
    messagingSenderId: '1009236955342',
    projectId: 'ecommerce-53a37',
    storageBucket: 'ecommerce-53a37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLX4TylF1Bzqz5Ud10nq55x_hAp2dTRQ4',
    appId: '1:1009236955342:ios:236553ac74dae9b28ec09f',
    messagingSenderId: '1009236955342',
    projectId: 'ecommerce-53a37',
    storageBucket: 'ecommerce-53a37.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );
}
